package com.agroprod.util;

import java.io.FileOutputStream;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import org.springframework.stereotype.Component;

import com.agroprod.model.Seller;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Component
public class PDFGenerator {

	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);

	private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

	public void generatePDF(String filePath, String customerName, String email, String customerAddress,
			String itemaName, double price, int quantity, int rate, String paymentId,Seller seller) {
		try {
			Document document = new Document();
			PdfWriter.getInstance(document, new FileOutputStream(filePath));
			document.open();
			addMetaData(document);
			addTitleAndTable(document, customerName, email, customerAddress, itemaName, price, quantity, rate,
					paymentId,seller);

			document.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static void addMetaData(Document document) {
		document.addTitle("My first PDF");
		document.addSubject("Using iText");
		document.addKeywords("Java, PDF, iText");
		document.addAuthor("Lars Vogel");
		document.addCreator("Lars Vogel");
	}

	private static void addTitleAndTable(Document document, String customerName, String email, String customerAddress,
			String itemaName, double price,int quantity,int rate,String paymentId,Seller seller) throws DocumentException {

		Paragraph preface = new Paragraph();
		
		preface.add(new Paragraph("Order Invoice", catFont));
		
		
		preface.add(new Paragraph("Report generated by: " + "AgroProduct App " + ", " + new Date(), smallBold));

		document.add(preface);
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);

		PdfPTable table1 = new PdfPTable(2);
		table1.setWidthPercentage(100);

		PdfPCell c1 = new PdfPCell(new Phrase("Customer Details "));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setColspan(2);
		table1.addCell(c1);

		table1.addCell("Customer Name");
		table1.addCell(customerName);

		table1.addCell("Email Id");
		table1.addCell(email);

		table1.addCell("Address");
		table1.addCell(customerAddress);

		document.add(table1);

		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		
		PdfPTable table3 = new PdfPTable(2);
		table3.setWidthPercentage(100);

		PdfPCell c3 = new PdfPCell(new Phrase("Seller Details "));
		c3.setHorizontalAlignment(Element.ALIGN_CENTER);
		c3.setColspan(2);
		table3.addCell(c3);

		table3.addCell("Seller Name");
		table3.addCell(seller.getSellerName());
		
		table3.addCell("Company");
		table3.addCell(seller.getSellerCompany());

		table3.addCell("Address");
		table3.addCell(seller.getSellerAddress());
		
		table3.addCell("Contact");
		table3.addCell(seller.getSellerContact());
		
		table3.addCell("Email");	
		table3.addCell(seller.getSellerEmail());

		table3.addCell("Website");
		table3.addCell(seller.getSellerWebsite());
		
		document.add(table3);
		
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		
		PdfPTable table2 = new PdfPTable(2);
		table2.setWidthPercentage(100);

		PdfPCell c2 = new PdfPCell(new Phrase("Order Details "));
		c2.setHorizontalAlignment(Element.ALIGN_CENTER);
		c2.setColspan(2);
		table2.addCell(c2);

		table2.addCell("Product Name");
		table2.addCell(itemaName);

		table2.addCell("Rate Per KG");
		table2.addCell(String.valueOf(rate+".00 /-"));
		
		table2.addCell("Quantity");
		table2.addCell(String.valueOf(quantity+" KG"));
		
		table2.addCell("Paid On");
		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
		LocalDateTime now = LocalDateTime.now();
		table2.addCell(dtf.format(now));

		table2.addCell("Payment Reference ID");
		table2.addCell(String.valueOf(paymentId));
		
		table2.addCell("Amount in Rs.");
		table2.addCell(String.valueOf(price+" /-"));

		document.add(table2);
		
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		
		Paragraph preface2 = new Paragraph();

		preface2.add(new Paragraph("Note :", catFont));
		preface2.add(new Paragraph("Refer Seller Details table for seller contact/address.", smallBold));
		preface2.add(new Paragraph("If you have any query please contact seller directly.", smallBold));
		preface2.add(new Paragraph("To collect/receive the order, Invoice is mandatory", smallBold));

		document.add(preface2);

		document.close();
	}
}
